version: "3.9"

services:

  # ── PostgreSQL ───────────────────────────────────────────────────────
  postgres:
    image: postgres:15-alpine
    container_name: skin_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10062004
      POSTGRES_DB: faceskin_ai_system

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - skin_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d faceskin_ai_system"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # ── FastAPI Backend ──────────────────────────────────────────────────
  backend:
    build:
      context: .                        # ROOT vì lệnh: uvicorn backend.main:app
      dockerfile: backend/Dockerfile
    container_name: skin_backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:10062004@postgres:5432/faceskin_ai_system
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: skin-images
      CLASSIFICATION_MODEL_PATH: backend/models/final_best.keras
      YOLO_MODEL_PATH: backend/models/best.pt
    volumes:
      - .:/app                                  # mount root cho hot-reload
      - ./backend/models:/backend/models    # mount model files
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - skin_net
    restart: unless-stopped

  # ── React Frontend (Vite → Nginx) ────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skin_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - skin_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  skin_net:
    driver: bridge
